services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
  balance:
    image: cashinoonline/cashino-balance-api
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=balance.local
    env_file:
      - ~/compose/balanceEnv.env
  casino:
    image: cashinoonline/cashino-api
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=casino.local
    env_file:
      - ~/compose/casinoEnv.env
  iframes:
    image: cashinoonline/cashino-iframes
    expose:
      - 80      
    environment:
      - VIRTUAL_HOST=iframes.local
