services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
  casino:
    image: cashinoonline/cashino-api
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=casino.cashino.online
    env_file:
      - casinoEnv.env
  iframes:
    image: cashinoonline/cashino-iframes
    expose:
      - 80      
    environment:
      - VIRTUAL_HOST=iframes.cashino.online
  home:
    image: cashinoonline/cashino-home
    expose:
      - 80
      - 443      
    environment:
      - VIRTUAL_HOST=cashino.online
  balance:
    image: cashinoonline/cashino-balance-api
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=balance.cashino.online
    env_file:
      - balanceEnv.env
  games:
    image: cashinoonline/cashino-games
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=games.cashino.online
    env_file:
      - gamesEnv.env
  bets:
    image: cashinoonline/cashino-bets
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=bets.cashino.online
    env_file:
      - betsEnv.env
